# fly.toml app configuration file generated for grafana-derby on 2025-06-06T01:24:46+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grafana-derby'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  GF_AUTH_ANONYMOUS_ENABLED = 'true'
  GF_AUTH_ANONYMOUS_ORG_NAME = 'Main Org.'
  GF_AUTH_ANONYMOUS_ORG_ROLE = 'Admin'
  GF_AUTH_DISABLE_LOGIN_FORM = 'true'
  GF_AUTH_DISABLE_SIGNOUT_MENU = 'true'
  GF_SECURITY_DISABLE_GRAVATAR = 'true'
  GF_SERVER_DOMAIN = 'grafana-derby.fly.dev/'
  GF_SERVER_ENFORCE_DOMAIN = 'false'
  GF_SERVER_HTTP_PORT = '3000'
  GF_SERVER_PROTOCOL = 'http'
  GF_SERVER_ROOT_URL = 'https://grafana-derby.fly.dev/'
  GF_USERS_ALLOW_SIGN_UP = 'false'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
