version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chain_derby_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chain_derby
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional pgAdmin for database management via web UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: chain_derby_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chainderbydemo.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password  # Change this in production
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: chain_derby_postgres_data