# fly.toml app configuration file generated for derby-api on 2025-06-05T01:18:12+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'derby-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
